#for this to work, ill need to run CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .` first
# I'm working off of this example https://blog.codeship.com/building-minimal-docker-containers-for-go-applications/

From scratch
Add main /
CMD ["/main"]